# Generated by Django 5.0.6 on 2024-05-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productmodel_alter_categorymodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='title',
            field=models.CharField(help_text='Тут вы должны написать название вашего продукта', max_length=100),
        ),
    ]
