# Generated by Django 5.0.6 on 2024-05-30 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_cartmodel_newscategory_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartmodel',
            options={'verbose_name_plural': 'Cart Models'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name_plural': 'News Categories'},
        ),
    ]
